// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayZone.Data;

#nullable disable

namespace PlayZone.Migrations
{
    [DbContext(typeof(PlayZoneDbContext))]
    [Migration("20251110121538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayZone.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("admin_users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 435, DateTimeKind.Utc).AddTicks(6199),
                            PasswordHash = "$2a$11$YPInZtySVXY/u6LPHiyMIOj.XnL0z.NMvgUhKul7EpgGgnjCq6ch6",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PlayZone.Models.BlockedSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("end_time");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Date");

                    b.HasIndex("RoomId", "Date", "StartTime", "EndTime");

                    b.ToTable("blocked_slots");
                });

            modelBuilder.Entity("PlayZone.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_phone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric")
                        .HasColumnName("duration");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("end_time");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("RoomId", "Date");

                    b.HasIndex("Date", "StartTime", "EndTime");

                    b.HasIndex("RoomId", "Date", "StartTime", "EndTime");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("PlayZone.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Available")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("available");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8828),
                            Description = "PlayStation Gaming Room 1",
                            Name = "Room 1",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8829)
                        },
                        new
                        {
                            Id = 2,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8832),
                            Description = "PlayStation Gaming Room 2",
                            Name = "Room 2",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8832)
                        },
                        new
                        {
                            Id = 3,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8834),
                            Description = "PlayStation Gaming Room 3",
                            Name = "Room 3",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8835)
                        },
                        new
                        {
                            Id = 4,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8837),
                            Description = "PlayStation Gaming Room 4",
                            Name = "Room 4",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8837)
                        },
                        new
                        {
                            Id = 5,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8839),
                            Description = "PlayStation Gaming Room 5",
                            Name = "Room 5",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8839)
                        },
                        new
                        {
                            Id = 6,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8842),
                            Description = "PlayStation Gaming Room 6",
                            Name = "Room 6",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8842)
                        },
                        new
                        {
                            Id = 7,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8845),
                            Description = "PlayStation Gaming Room 7",
                            Name = "Room 7",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8845)
                        },
                        new
                        {
                            Id = 8,
                            Available = true,
                            CreatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8847),
                            Description = "PlayStation Gaming Room 8",
                            Name = "Room 8",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 312, DateTimeKind.Utc).AddTicks(8847)
                        });
                });

            modelBuilder.Entity("PlayZone.Models.WhatsAppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("business_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("whatsapp_config");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessNumber = "+201234567890",
                            UpdatedAt = new DateTime(2025, 11, 10, 12, 15, 36, 435, DateTimeKind.Utc).AddTicks(7837)
                        });
                });

            modelBuilder.Entity("PlayZone.Models.BlockedSlot", b =>
                {
                    b.HasOne("PlayZone.Models.Room", "Room")
                        .WithMany("BlockedSlots")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PlayZone.Models.Booking", b =>
                {
                    b.HasOne("PlayZone.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PlayZone.Models.Room", b =>
                {
                    b.Navigation("BlockedSlots");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
